"""Pydantic models for the consolidation pipeline stage.

The consolidation stage operates *across* all extracted issues to detect
duplicates, group issues by domain, and produce project-level enrichment
such as capability maps and cross-cutting concerns.

Models
------
- :class:`DuplicateRequirement` — A detected duplicate pair with a canonical form.
- :class:`DomainGroup` — A logical module/domain grouping of issues.
- :class:`ProjectEnrichment` — LLM-generated project-level insights.
- :class:`ConsolidationResult` — Full output of the consolidation stage.
"""

from __future__ import annotations

from pydantic import BaseModel, Field


class DuplicateRequirement(BaseModel):
    """A pair of requirements detected as semantically duplicated.

    Includes the original text from both issues and a recommended
    canonical form so that downstream stages can merge or flag them.
    """

    issue_key_a: str
    issue_key_b: str
    requirement_a: str
    requirement_b: str
    similarity_reason: str
    recommended_canonical: str = Field(
        description="The canonical form to keep"
    )


class DomainGroup(BaseModel):
    """A logical domain or module grouping of related issues.

    Domain groups help organise large backlogs into coherent functional
    areas (e.g. *Authentication*, *Payments*, *User Profile*).
    """

    domain_name: str = Field(
        description="e.g. 'Authentication', 'Payments', 'User Profile'"
    )
    description: str = ""
    issue_keys: list[str] = Field(default_factory=list)
    key_capabilities: list[str] = Field(default_factory=list)


class ProjectEnrichment(BaseModel):
    """Project-level enrichment generated by the consolidation LLM.

    Provides a bird's-eye view of the project including a natural-language
    summary, domain decomposition, recurring themes, and a capability map
    linking capabilities to the issues that implement them.
    """

    project_summary: str = Field(
        description="High-level summary of the entire project"
    )
    domain_groups: list[DomainGroup] = Field(default_factory=list)
    key_themes: list[str] = Field(
        default_factory=list,
        description="Major themes across all issues",
    )
    cross_cutting_concerns: list[str] = Field(
        default_factory=list,
        description="NFRs/concerns that span multiple issues",
    )
    capability_map: dict[str, list[str]] = Field(
        default_factory=dict,
        description="capability -> [issue_keys]",
    )


class ConsolidationResult(BaseModel):
    """Full output of the consolidation stage.

    Aggregates deduplication findings, enrichment data, and bookkeeping
    counters so that downstream reporters can produce a comprehensive
    project-level summary.
    """

    total_issues_processed: int = 0
    duplicate_requirements: list[DuplicateRequirement] = Field(
        default_factory=list
    )
    merged_requirement_count: int = 0
    enrichment: ProjectEnrichment = Field(default_factory=ProjectEnrichment)
    issues_updated: int = 0
    consolidation_notes: list[str] = Field(default_factory=list)
